#!/bin/bash
#PBS -q normal
#PBS -N atmFlatTerrain
#PBS -l select=1:ncpus=64:mpiprocs=64:mem=128G
#PBS -m abe
#PBS -M E1137075@u.nus.edu
#PBS -l walltime=24:00:00
#PBS -P 13003612

cd "$PBS_O_WORKDIR"

###source /home/project/13003612/OpenFOAM/foam-extend-4.1/etc/bashrc

module load openfoam/2412

./Allrun > log.Allrun 2>&1

echo "=== JOB COMPLETE ==="
