#!/bin/sh
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

RASModel="kEpsilon"    # "kOmegaSST"

sed -e "s|RAS_MODEL|$RASModel|g" \
    constant/turbulenceProperties.template \
  > constant/turbulenceProperties

restore0Dir

cp -rf constant/polyMesh.orig constant/polyMesh

runApplication mapFields ../precursor -sourceTime latestTime

runApplication decomposePar -force

runParallel renumberMesh -overwrite

runParallel $(getApplication)

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
